//=======================================================
// This code is generated by Brena Marques
//=======================================================
module TESTE1(
	//////////// CLOCK ////////////
input				CLOCK_50MHz,
input				CLOCK1_50MHz,

//////////// LED_MATRIX //////////
output	[4:0]	LEDM_C,
output	[7:0]	LEDM_R,

//////////// VGA //////////
output	[3:0]	VGA_R,
output	[3:0]	VGA_G,
output	[3:0]	VGA_B,
output				VGA_HS,
output				VGA_VS,

);

//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================




endmodule
